-- MySQL Script generated by MySQL Workbench
-- Sat Apr 10 23:18:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siteDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siteDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siteDB` DEFAULT CHARACTER SET utf8 ;
USE `siteDB` ;

-- -----------------------------------------------------
-- Table `siteDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siteDB`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(12) NULL,
  `vk_link` VARCHAR(40) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteDB`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siteDB`.`projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `imprint` BLOB NULL,
  `shortdescription` VARCHAR(200) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteDB`.`problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siteDB`.`problems` (
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_problems_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `siteDB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteDB`.`projects_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siteDB`.`projects_has_users` (
  `projects_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`projects_id`, `users_id`),
  INDEX `fk_projects_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_projects_has_users_projects1_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_has_users_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `siteDB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `siteDB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
